title:        'Mike Funk'
tagline:      'Web Developer'
description:  "Hi, I'm Mike. I'm a web developer. This is my story."
excerpt_separator: <!--more-->
url:          ''
version:      1.1.1
author:
  name:       'Mike Funk'
  email:      'mike@mikefunk.com'
markdown:     rdiscount
permalink:    pretty
highlighter:  true
paginate:     5
plugins: [jekyll-paginate]
