title:        'Mike Funk'
tagline:      'Web Developer'
description:  "Hi, I'm Mike. I'm a web developer. This is my story."
url:          http://mikefunk.com
version:      1.1.1
author:
  name:       'Mike Funk'
  email:      'mike@mikefunk.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
